package com.yang.dao;

import com.yang.bean.TAopContract;
import java.util.List;

public interface TAopContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aop_contract
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String contractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aop_contract
     *
     * @mbggenerated
     */
    int insert(TAopContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aop_contract
     *
     * @mbggenerated
     */
    TAopContract selectByPrimaryKey(String contractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aop_contract
     *
     * @mbggenerated
     */
    List<TAopContract> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aop_contract
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TAopContract record);
}