package com.yang.bean;

import java.io.Serializable;
import java.util.Date;

public class TAopContract implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.CONTRACT_ID
     *
     * @mbggenerated
     */
    private String contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.TENANT_ID
     *
     * @mbggenerated
     */
    private String tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.COMPANY_NAME
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.OPENING_BANK
     *
     * @mbggenerated
     */
    private String openingBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.REPRESENTATIVE
     *
     * @mbggenerated
     */
    private String representative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.TELEPHONE
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.STATE_TAX_NUM
     *
     * @mbggenerated
     */
    private String stateTaxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.OPENING_NAME
     *
     * @mbggenerated
     */
    private String openingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.COMPANY_ADDRESS
     *
     * @mbggenerated
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.BANK_CRAD
     *
     * @mbggenerated
     */
    private String bankCrad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.CONTACTS
     *
     * @mbggenerated
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.CONTRACT_YEAE
     *
     * @mbggenerated
     */
    private String contractYeae;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.SERVICE_COST
     *
     * @mbggenerated
     */
    private Double serviceCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.PACKAGE_SUM
     *
     * @mbggenerated
     */
    private Double packageSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.CREATE_USER
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.EFFECTIVE_TIME
     *
     * @mbggenerated
     */
    private Date effectiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.FAILURE_TIME
     *
     * @mbggenerated
     */
    private Date failureTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.CONTRACT_STATUS
     *
     * @mbggenerated
     */
    private String contractStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.FST_CHAR_ATTR_VAL
     *
     * @mbggenerated
     */
    private String fstCharAttrVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.SECD_CHAR_ATTR_VAL
     *
     * @mbggenerated
     */
    private String secdCharAttrVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aop_contract.THRD_CHAR_ATTR_VAL
     *
     * @mbggenerated
     */
    private String thrdCharAttrVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_aop_contract
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.CONTRACT_ID
     *
     * @return the value of t_aop_contract.CONTRACT_ID
     *
     * @mbggenerated
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.CONTRACT_ID
     *
     * @param contractId the value for t_aop_contract.CONTRACT_ID
     *
     * @mbggenerated
     */
    public void setContractId(String contractId) {
        this.contractId = contractId == null ? null : contractId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.TENANT_ID
     *
     * @return the value of t_aop_contract.TENANT_ID
     *
     * @mbggenerated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.TENANT_ID
     *
     * @param tenantId the value for t_aop_contract.TENANT_ID
     *
     * @mbggenerated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.COMPANY_NAME
     *
     * @return the value of t_aop_contract.COMPANY_NAME
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.COMPANY_NAME
     *
     * @param companyName the value for t_aop_contract.COMPANY_NAME
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.OPENING_BANK
     *
     * @return the value of t_aop_contract.OPENING_BANK
     *
     * @mbggenerated
     */
    public String getOpeningBank() {
        return openingBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.OPENING_BANK
     *
     * @param openingBank the value for t_aop_contract.OPENING_BANK
     *
     * @mbggenerated
     */
    public void setOpeningBank(String openingBank) {
        this.openingBank = openingBank == null ? null : openingBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.REPRESENTATIVE
     *
     * @return the value of t_aop_contract.REPRESENTATIVE
     *
     * @mbggenerated
     */
    public String getRepresentative() {
        return representative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.REPRESENTATIVE
     *
     * @param representative the value for t_aop_contract.REPRESENTATIVE
     *
     * @mbggenerated
     */
    public void setRepresentative(String representative) {
        this.representative = representative == null ? null : representative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.EMAIL
     *
     * @return the value of t_aop_contract.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.EMAIL
     *
     * @param email the value for t_aop_contract.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.TELEPHONE
     *
     * @return the value of t_aop_contract.TELEPHONE
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.TELEPHONE
     *
     * @param telephone the value for t_aop_contract.TELEPHONE
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.STATE_TAX_NUM
     *
     * @return the value of t_aop_contract.STATE_TAX_NUM
     *
     * @mbggenerated
     */
    public String getStateTaxNum() {
        return stateTaxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.STATE_TAX_NUM
     *
     * @param stateTaxNum the value for t_aop_contract.STATE_TAX_NUM
     *
     * @mbggenerated
     */
    public void setStateTaxNum(String stateTaxNum) {
        this.stateTaxNum = stateTaxNum == null ? null : stateTaxNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.OPENING_NAME
     *
     * @return the value of t_aop_contract.OPENING_NAME
     *
     * @mbggenerated
     */
    public String getOpeningName() {
        return openingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.OPENING_NAME
     *
     * @param openingName the value for t_aop_contract.OPENING_NAME
     *
     * @mbggenerated
     */
    public void setOpeningName(String openingName) {
        this.openingName = openingName == null ? null : openingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.COMPANY_ADDRESS
     *
     * @return the value of t_aop_contract.COMPANY_ADDRESS
     *
     * @mbggenerated
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.COMPANY_ADDRESS
     *
     * @param companyAddress the value for t_aop_contract.COMPANY_ADDRESS
     *
     * @mbggenerated
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.BANK_CRAD
     *
     * @return the value of t_aop_contract.BANK_CRAD
     *
     * @mbggenerated
     */
    public String getBankCrad() {
        return bankCrad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.BANK_CRAD
     *
     * @param bankCrad the value for t_aop_contract.BANK_CRAD
     *
     * @mbggenerated
     */
    public void setBankCrad(String bankCrad) {
        this.bankCrad = bankCrad == null ? null : bankCrad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.CONTACTS
     *
     * @return the value of t_aop_contract.CONTACTS
     *
     * @mbggenerated
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.CONTACTS
     *
     * @param contacts the value for t_aop_contract.CONTACTS
     *
     * @mbggenerated
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.CONTRACT_YEAE
     *
     * @return the value of t_aop_contract.CONTRACT_YEAE
     *
     * @mbggenerated
     */
    public String getContractYeae() {
        return contractYeae;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.CONTRACT_YEAE
     *
     * @param contractYeae the value for t_aop_contract.CONTRACT_YEAE
     *
     * @mbggenerated
     */
    public void setContractYeae(String contractYeae) {
        this.contractYeae = contractYeae == null ? null : contractYeae.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.SERVICE_COST
     *
     * @return the value of t_aop_contract.SERVICE_COST
     *
     * @mbggenerated
     */
    public Double getServiceCost() {
        return serviceCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.SERVICE_COST
     *
     * @param serviceCost the value for t_aop_contract.SERVICE_COST
     *
     * @mbggenerated
     */
    public void setServiceCost(Double serviceCost) {
        this.serviceCost = serviceCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.PACKAGE_SUM
     *
     * @return the value of t_aop_contract.PACKAGE_SUM
     *
     * @mbggenerated
     */
    public Double getPackageSum() {
        return packageSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.PACKAGE_SUM
     *
     * @param packageSum the value for t_aop_contract.PACKAGE_SUM
     *
     * @mbggenerated
     */
    public void setPackageSum(Double packageSum) {
        this.packageSum = packageSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.CREATE_USER
     *
     * @return the value of t_aop_contract.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.CREATE_USER
     *
     * @param createUser the value for t_aop_contract.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.CREATE_TIME
     *
     * @return the value of t_aop_contract.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.CREATE_TIME
     *
     * @param createTime the value for t_aop_contract.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.EFFECTIVE_TIME
     *
     * @return the value of t_aop_contract.EFFECTIVE_TIME
     *
     * @mbggenerated
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.EFFECTIVE_TIME
     *
     * @param effectiveTime the value for t_aop_contract.EFFECTIVE_TIME
     *
     * @mbggenerated
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.FAILURE_TIME
     *
     * @return the value of t_aop_contract.FAILURE_TIME
     *
     * @mbggenerated
     */
    public Date getFailureTime() {
        return failureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.FAILURE_TIME
     *
     * @param failureTime the value for t_aop_contract.FAILURE_TIME
     *
     * @mbggenerated
     */
    public void setFailureTime(Date failureTime) {
        this.failureTime = failureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.CONTRACT_STATUS
     *
     * @return the value of t_aop_contract.CONTRACT_STATUS
     *
     * @mbggenerated
     */
    public String getContractStatus() {
        return contractStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.CONTRACT_STATUS
     *
     * @param contractStatus the value for t_aop_contract.CONTRACT_STATUS
     *
     * @mbggenerated
     */
    public void setContractStatus(String contractStatus) {
        this.contractStatus = contractStatus == null ? null : contractStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.FST_CHAR_ATTR_VAL
     *
     * @return the value of t_aop_contract.FST_CHAR_ATTR_VAL
     *
     * @mbggenerated
     */
    public String getFstCharAttrVal() {
        return fstCharAttrVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.FST_CHAR_ATTR_VAL
     *
     * @param fstCharAttrVal the value for t_aop_contract.FST_CHAR_ATTR_VAL
     *
     * @mbggenerated
     */
    public void setFstCharAttrVal(String fstCharAttrVal) {
        this.fstCharAttrVal = fstCharAttrVal == null ? null : fstCharAttrVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.SECD_CHAR_ATTR_VAL
     *
     * @return the value of t_aop_contract.SECD_CHAR_ATTR_VAL
     *
     * @mbggenerated
     */
    public String getSecdCharAttrVal() {
        return secdCharAttrVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.SECD_CHAR_ATTR_VAL
     *
     * @param secdCharAttrVal the value for t_aop_contract.SECD_CHAR_ATTR_VAL
     *
     * @mbggenerated
     */
    public void setSecdCharAttrVal(String secdCharAttrVal) {
        this.secdCharAttrVal = secdCharAttrVal == null ? null : secdCharAttrVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aop_contract.THRD_CHAR_ATTR_VAL
     *
     * @return the value of t_aop_contract.THRD_CHAR_ATTR_VAL
     *
     * @mbggenerated
     */
    public String getThrdCharAttrVal() {
        return thrdCharAttrVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aop_contract.THRD_CHAR_ATTR_VAL
     *
     * @param thrdCharAttrVal the value for t_aop_contract.THRD_CHAR_ATTR_VAL
     *
     * @mbggenerated
     */
    public void setThrdCharAttrVal(String thrdCharAttrVal) {
        this.thrdCharAttrVal = thrdCharAttrVal == null ? null : thrdCharAttrVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aop_contract
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", contractId=").append(contractId);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", companyName=").append(companyName);
        sb.append(", openingBank=").append(openingBank);
        sb.append(", representative=").append(representative);
        sb.append(", email=").append(email);
        sb.append(", telephone=").append(telephone);
        sb.append(", stateTaxNum=").append(stateTaxNum);
        sb.append(", openingName=").append(openingName);
        sb.append(", companyAddress=").append(companyAddress);
        sb.append(", bankCrad=").append(bankCrad);
        sb.append(", contacts=").append(contacts);
        sb.append(", contractYeae=").append(contractYeae);
        sb.append(", serviceCost=").append(serviceCost);
        sb.append(", packageSum=").append(packageSum);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", effectiveTime=").append(effectiveTime);
        sb.append(", failureTime=").append(failureTime);
        sb.append(", contractStatus=").append(contractStatus);
        sb.append(", fstCharAttrVal=").append(fstCharAttrVal);
        sb.append(", secdCharAttrVal=").append(secdCharAttrVal);
        sb.append(", thrdCharAttrVal=").append(thrdCharAttrVal);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}